---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/6/13 15:22
---

--1.参数列表
-- 1.1 优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]
-- 1.3 订单id
local orderId = ARGV[3]
-- 2数据
--2.1 库存key
local stockKey = "seckill:stock:" .. voucherId
--2.2 订单key
local orderKey = "seckill:order:" .. voucherId
local reservationKey = "seckill:reservation:" .. orderId
local reservationIndexKey = "seckill:reservation:index"

-- 3 脚本业务
-- 3.1 判断库存是否充足 get stockKey
if(tonumber(redis.call("get", stockKey)) <= 0) then
    return 1 --库存不足
end
-- 3.2 判断用户是否重复下单 SISMENBER orderKey userId
if(redis.call("sismember", orderKey, userId) == 1) then
    return 2 --用户重复下单
end

-- 3.3 扣减库存 incrby stockKey -1
redis.call("incrby", stockKey, -1)
-- 3.4 记录订单 sadd orderKey userId
redis.call("sadd", orderKey, userId)
-- 3.5 记录预扣状态。订单消息只由 RabbitMQ 生产者投递，避免 Redis Stream 双通道重复消费。
local reservedAt = redis.call("time")[1]
redis.call("hset", reservationKey,
    "orderId", orderId,
    "userId", userId,
    "voucherId", voucherId,
    "reservedAt", reservedAt,
    "status", "PENDING")
redis.call("expire", reservationKey, 86400)
redis.call("zadd", reservationIndexKey, reservedAt, orderId)
-- 4 返回结果
return 0 --下单成功
